(1.0, (('treats', 'X', 'Y'), ('has_target', 'X', 'A4'), ('interacts', 'A4', 'A5'), ('associates', 'A5', 'Y')))
(1.0, (('treats', 'X', 'Y'), ('has_target', 'X', 'A4'), ('interacts', 'A4', 'A5'), ('treats', 'A5', 'Y')))
(1.0, (('treats', 'X', 'Y'), ('treats', 'X', 'Y')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('has_mechanism', 'A4', 'g5')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('associates', 'A4', 'd1')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('has_mechanism', 'A4', 'm2')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'd1')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'g2')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('participates', 'A3', 'A4'), ('interacts', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('participates', 'A3', 'A4'), ('interacts', 'A4', 'g2')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('participates', 'A3', 'A4'), ('participates', 'A4', 'g2')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('participates', 'A3', 'A4'), ('participates', 'A4', 'g3')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'A3'), ('participates', 'A3', 'p1')))
(1.0, (('treats', 'X', 'd1'), ('has_target', 'X', 'g1')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('associates', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('associates', 'A4', 'd3')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('has_mechanism', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('has_mechanism', 'A4', 'm1')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('interacts', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('interacts', 'A4', 'g4')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('interacts', 'A4', 'g5')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('participates', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('participates', 'A4', 'p1')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'A3'), ('has_target', 'A3', 'g3')))
(1.0, (('treats', 'X', 'd1'), ('resembles', 'X', 'c2')))
(1.0, (('treats', 'X', 'd1'), ('treats', 'X', 'd1')))
(1.0, (('treats', 'X', 'd1'), ('treats', 'd1', 'X')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('has_mechanism', 'A4', 'g1')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('interacts', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('interacts', 'A4', 'g3')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('associates', 'A4', 'd3')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('has_mechanism', 'A4', 'm1')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('has_target', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('has_target', 'A4', 'c2')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('interacts', 'A4', 'A5')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('interacts', 'A4', 'g4')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'd3')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('interacts', 'A3', 'g3')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('participates', 'A3', 'A4'), ('participates', 'A4', 'g4')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'A3'), ('participates', 'A3', 'p2')))
(1.0, (('treats', 'X', 'd3'), ('has_target', 'X', 'g5')))
(1.0, (('treats', 'X', 'd3'), ('treats', 'X', 'd3')))
(1.0, (('treats', 'X', 'd3'), ('treats', 'd3', 'X')))
(1.0, (('treats', 'Y', 'X'), ('associates', 'X', 'A4'), ('interacts', 'A4', 'A5'), ('has_target', 'A5', 'Y')))
(1.0, (('treats', 'Y', 'X'), ('associates', 'X', 'A4'), ('interacts', 'A4', 'A5'), ('treats', 'A5', 'Y')))
(1.0, (('treats', 'Y', 'd1'), ('associates', 'd1', 'A3'), ('interacts', 'A3', 'A4'), ('has_target', 'A4', 'Y')))
(1.0, (('treats', 'Y', 'd1'), ('associates', 'd1', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'Y')))
(1.0, (('treats', 'Y', 'd3'), ('associates', 'd3', 'A3'), ('interacts', 'A3', 'A4'), ('has_target', 'A4', 'Y')))
(1.0, (('treats', 'Y', 'd3'), ('associates', 'd3', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'Y')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('has_mechanism', 'A4', 'g4')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('has_mechanism', 'A3', 'm2')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('has_target', 'A4', 'c1')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('participates', 'A4', 'p1')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'c1')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'g1')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('participates', 'A3', 'A4'), ('interacts', 'A4', 'A5')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('participates', 'A3', 'A4'), ('interacts', 'A4', 'g1')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'A3'), ('participates', 'A3', 'A4'), ('participates', 'A4', 'g3')))
(1.0, (('treats', 'c1', 'X'), ('associates', 'X', 'g2')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'A4'), ('has_mechanism', 'A4', 'm1')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'A4'), ('has_target', 'A4', 'A5')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'A4'), ('has_target', 'A4', 'c2')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'A4'), ('interacts', 'A4', 'g4')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'A4'), ('interacts', 'A4', 'g5')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'g3')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4'), ('has_target', 'A4', 'A5')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4'), ('has_target', 'A4', 'g5')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'c3')))
(1.0, (('treats', 'c1', 'X'), ('resembles', 'X', 'd3')))
(1.0, (('treats', 'c1', 'Y'), ('has_target', 'c1', 'A3'), ('interacts', 'A3', 'A4'), ('associates', 'A4', 'Y')))
(1.0, (('treats', 'c1', 'Y'), ('has_target', 'c1', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'Y')))
(1.0, (('treats', 'c1', 'Y'), ('treats', 'c1', 'Y')))
(1.0, (('treats', 'c1', 'd1'), ('treats', 'd1', 'c1')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('has_mechanism', 'A4', 'g1')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('has_mechanism', 'A4', 'g5')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('interacts', 'A4', 'A5')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_mechanism', 'A3', 'A4'), ('interacts', 'A4', 'g5')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_mechanism', 'A3', 'm1')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_target', 'A3', 'A4')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('resembles', 'A4', 'A5')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_target', 'A3', 'A4'), ('resembles', 'A4', 'c1')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('has_target', 'A3', 'c2')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('associates', 'A4', 'A5')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('associates', 'A4', 'd2')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('has_mechanism', 'A4', 'm2')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('has_target', 'A4', 'c3')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('participates', 'A4', 'p2')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'c3')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'g4')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('interacts', 'A3', 'g5')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'A3'), ('participates', 'A3', 'A4'), ('participates', 'A4', 'g2')))
(1.0, (('treats', 'c3', 'X'), ('associates', 'X', 'g3')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'A4'), ('has_mechanism', 'A4', 'm2')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'A4'), ('interacts', 'A4', 'g1')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('associates', 'A3', 'g2')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4'), ('has_target', 'A4', 'A5')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4'), ('has_target', 'A4', 'g1')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4'), ('resembles', 'A4', 'A5')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'A4'), ('resembles', 'A4', 'c2')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'A3'), ('treats', 'A3', 'c1')))
(1.0, (('treats', 'c3', 'X'), ('resembles', 'X', 'd1')))
(1.0, (('treats', 'c3', 'Y'), ('has_target', 'c3', 'A3'), ('interacts', 'A3', 'A4'), ('associates', 'A4', 'Y')))
(1.0, (('treats', 'c3', 'Y'), ('has_target', 'c3', 'A3'), ('interacts', 'A3', 'A4'), ('treats', 'A4', 'Y')))
(1.0, (('treats', 'c3', 'Y'), ('treats', 'c3', 'Y')))
(1.0, (('treats', 'c3', 'd3'), ('treats', 'd3', 'c3')))
